/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import datos.DLibros;
import javax.swing.JOptionPane;
import logica.LLibros;

/**
 *
 * @author FeedzOne
 */
public class FrmAgregarLibros extends javax.swing.JFrame {

    /**
     * Creates new form FrmAgregarLibros
     */
    public FrmAgregarLibros() {
        initComponents();
        idEF.setVisible(false);
        idEF.setEditable(false);
        idGF.setVisible(false);
        idGF.setEditable(false);
        IDAField.setVisible(false);
        IDAField.setEditable(false);
        EditorialField.setEditable(false);
        AutorField.setEditable(false);
        GeneroField.setEditable(false);
        EditorialField.setEnabled(false);
        AutorField.setEnabled(false);
        GeneroField.setEnabled(false);
    }
    
    public static void setEditorial(String id, String editorial){
        idEF.setText(id);
        EditorialField.setText(editorial);
    }
    
    public static void setGenero(String id, String genero){
        idGF.setText(id);
        GeneroField.setText(genero);
    }
    
    public static void setAutor(String id, String nombre){
        IDAField.setText(id);
        AutorField.setText(nombre);
    }
    public void clearField(){
        ISBNField.setText("");
        TituloField.setText("");
        DescField.setText("");
        EditorialField.setText("");
        EditionField.setText("");
        idEF.setText("");
        idGF.setText("");
        IDAField.setText("");
        AutorField.setText("");
        QtyField.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ISBNField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        DescField = new javax.swing.JTextArea();
        EditionField = new javax.swing.JTextField();
        QtyField = new javax.swing.JTextField();
        StatusField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        SaveBTN = new javax.swing.JButton();
        DeleteBTN = new javax.swing.JButton();
        AddAuthorBTN = new javax.swing.JButton();
        AddEditorialBTN = new javax.swing.JButton();
        AddGenreBTN = new javax.swing.JButton();
        EditorialField = new javax.swing.JTextField();
        GeneroField = new javax.swing.JTextField();
        BtnBuscaEditorial = new javax.swing.JButton();
        BtnBuscaGenero = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        TituloField = new javax.swing.JTextField();
        idEF = new javax.swing.JTextField();
        idGF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        BtnBuscarAutor = new javax.swing.JButton();
        AutorField = new javax.swing.JTextField();
        IDAField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(190, 230, 255));

        jLabel1.setText("ISBN:");

        jLabel2.setText("Descripcion:");

        jLabel3.setText("Editorial:");

        jLabel4.setText("Edicion:");

        jLabel6.setText("Cantidad:");

        jLabel7.setText("Genero:");

        jLabel10.setText("Estado del Libro:");

        DescField.setColumns(20);
        DescField.setRows(5);
        jScrollPane1.setViewportView(DescField);

        StatusField.setText("1");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 65)); // NOI18N
        jLabel11.setText("AGREGAR LIBROS");

        SaveBTN.setText("Guardar");
        SaveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBTNActionPerformed(evt);
            }
        });

        DeleteBTN.setText("Borrar Todo");
        DeleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBTNActionPerformed(evt);
            }
        });

        AddAuthorBTN.setText("Agregar Autor");
        AddAuthorBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAuthorBTNActionPerformed(evt);
            }
        });

        AddEditorialBTN.setText("Agregar Editorial");
        AddEditorialBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEditorialBTNActionPerformed(evt);
            }
        });

        AddGenreBTN.setText("Agregar Genero");
        AddGenreBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddGenreBTNActionPerformed(evt);
            }
        });

        BtnBuscaEditorial.setText("...");
        BtnBuscaEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscaEditorialActionPerformed(evt);
            }
        });

        BtnBuscaGenero.setText("...");
        BtnBuscaGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscaGeneroActionPerformed(evt);
            }
        });

        jLabel5.setText("Titulo");

        jLabel8.setText("Autor: ");

        BtnBuscarAutor.setText("...");
        BtnBuscarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarAutorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(DeleteBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SaveBTN)
                .addGap(46, 46, 46))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(QtyField, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ISBNField, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TituloField, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(EditionField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                                                    .addComponent(EditorialField, javax.swing.GroupLayout.Alignment.LEADING)))
                                            .addComponent(AutorField))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BtnBuscaEditorial)
                                            .addComponent(BtnBuscarAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(idEF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(idGF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(IDAField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(AddEditorialBTN)
                                            .addComponent(AddAuthorBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(175, 175, 175)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(GeneroField, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(StatusField, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(BtnBuscaGenero)
                                .addGap(18, 18, 18)
                                .addComponent(AddGenreBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(105, 105, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel11)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ISBNField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(TituloField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(39, 39, 39)))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(EditorialField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscaEditorial)
                    .addComponent(AddEditorialBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(EditionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idEF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idGF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDAField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(AutorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscarAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddAuthorBTN))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QtyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(AddGenreBTN)
                    .addComponent(BtnBuscaGenero)
                    .addComponent(GeneroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(StatusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteBTN)
                    .addComponent(SaveBTN))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBTNActionPerformed
        clearField();
    }//GEN-LAST:event_DeleteBTNActionPerformed

    private void AddAuthorBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAuthorBTNActionPerformed
        FrmAutores misAutores = new FrmAutores();
        misAutores.show();
    }//GEN-LAST:event_AddAuthorBTNActionPerformed

    private void AddEditorialBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEditorialBTNActionPerformed
        FrmEditoriales misEditoriales = new FrmEditoriales();
        misEditoriales.show();
    }//GEN-LAST:event_AddEditorialBTNActionPerformed

    private void AddGenreBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddGenreBTNActionPerformed
        FrmGeneroLibros misGeneros = new FrmGeneroLibros();
        misGeneros.show();
    }//GEN-LAST:event_AddGenreBTNActionPerformed

    private void SaveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBTNActionPerformed
        // TODO add your handling code here:
        if(ISBNField.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "El ISBN es Requerido", "Validacion", JOptionPane.WARNING_MESSAGE); 
            ISBNField.requestFocusInWindow();
            return;
        }
        if(TituloField.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "El titulo es Requerido", "Validacion", JOptionPane.WARNING_MESSAGE); 
            TituloField.requestFocusInWindow();
            return;
        }
        if(AutorField.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "El Autor es Requerido", "Validacion", JOptionPane.WARNING_MESSAGE); 
            AutorField.requestFocusInWindow();
            return;
        }
        if(DescField.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "La descripcion es Requerida", "Validacion", JOptionPane.WARNING_MESSAGE); 
            DescField.requestFocusInWindow();
            return;
        }
        if(EditorialField.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "La editorial es Requerida", "Validacion", JOptionPane.WARNING_MESSAGE); 
            EditorialField.requestFocusInWindow();
            return;
        }
        if(EditionField.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "La edicion es Requerida", "Validacion", JOptionPane.WARNING_MESSAGE); 
            EditionField.requestFocusInWindow();
            return;
        }
        if(QtyField.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "La cantidad es Requerida", "Validacion", JOptionPane.WARNING_MESSAGE); 
            QtyField.requestFocusInWindow();
            return;
        }
        if(GeneroField.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "El Genero es Requerido", "Validacion", JOptionPane.WARNING_MESSAGE); 
            GeneroField.requestFocusInWindow();
            return;
        }
        if(StatusField.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "El estado es Requerido", "Validacion", JOptionPane.WARNING_MESSAGE); 
            StatusField.requestFocusInWindow();
            return;
        }
        
        String msg = null;
        if(!ISBNField.getText().equals("")){
            DLibros dts = new DLibros();
            LLibros fun = new LLibros();
            dts.setISBN(ISBNField.getText());
            dts.setTitulo(TituloField.getText());
            dts.setDescripcion(DescField.getText());
            dts.setIdEditorial(Integer.parseInt(idEF.getText()));
            dts.setId_autor(Integer.parseInt(IDAField.getText()));
            dts.setEdicion(EditionField.getText());
            dts.setCantidad(Integer.parseInt(QtyField.getText()));
            dts.setId_genero(Integer.parseInt(idGF.getText()));
            dts.setIdEstadoLibro(Integer.parseInt(StatusField.getText()));
            msg = fun.insertarLibro(dts);
            if(msg == "si"){
               JOptionPane.showMessageDialog(rootPane, "Registrado Satisfactoriamente", "Info", JOptionPane.INFORMATION_MESSAGE); 
            }else
            {
                JOptionPane.showMessageDialog(rootPane, "Uh oh, ocurrió un error", "Info", JOptionPane.INFORMATION_MESSAGE); 
            }
        }
        clearField();
    }//GEN-LAST:event_SaveBTNActionPerformed

    private void BtnBuscaEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscaEditorialActionPerformed
        // TODO add your handling code here:
        FrmBuscaEditoriales be = new FrmBuscaEditoriales();
        be.setLocationRelativeTo(null);
        be.setVisible(true);
    }//GEN-LAST:event_BtnBuscaEditorialActionPerformed

    private void BtnBuscaGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscaGeneroActionPerformed
        // TODO add your handling code here:
        FrmBuscaGenero bg = new FrmBuscaGenero();
        bg.setLocationRelativeTo(null);
        bg.setVisible(true);
    }//GEN-LAST:event_BtnBuscaGeneroActionPerformed

    private void BtnBuscarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarAutorActionPerformed
        FrmBuscarAutor misAutores = new FrmBuscarAutor();
        misAutores.show();
    }//GEN-LAST:event_BtnBuscarAutorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAgregarLibros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddAuthorBTN;
    private javax.swing.JButton AddEditorialBTN;
    private javax.swing.JButton AddGenreBTN;
    private static javax.swing.JTextField AutorField;
    private javax.swing.JButton BtnBuscaEditorial;
    private javax.swing.JButton BtnBuscaGenero;
    private javax.swing.JButton BtnBuscarAutor;
    private javax.swing.JButton DeleteBTN;
    private javax.swing.JTextArea DescField;
    private javax.swing.JTextField EditionField;
    private static javax.swing.JTextField EditorialField;
    private static javax.swing.JTextField GeneroField;
    private static javax.swing.JTextField IDAField;
    private javax.swing.JTextField ISBNField;
    private javax.swing.JTextField QtyField;
    private javax.swing.JButton SaveBTN;
    private javax.swing.JTextField StatusField;
    private javax.swing.JTextField TituloField;
    private static javax.swing.JTextField idEF;
    private static javax.swing.JTextField idGF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
